### ISSUE TITLE
vbox build for `pfSense`

### ISSUE THREAD

**Issue by malice-0** [rylagek/pack_everything#25]
So we have a build that produces artifacts, however, packer is having issues connecting via ssh, even though manually importing the image confirms that sshd is running and root can login over ssh. IOT produce artifacts I disabled the ssh communicator.

This means that we can't run provisioners using packer in the current build. If this can't be figured out, one option is to load scripts over http (I believe pfSense is configured using scripts or an xml file). However, since sshd is definitely working, it could also be done in a chained build after the image is created, perhaps?

@rylagek

**Comment by malice-0** [comment]
Ok so I'm an idiot and swapped the username and password in the packer file. Fixing and retesting now

**Comment by malice-0** [comment]
This was indeed the issue, packer now successfully builds and connects.
As noted in the build notes, had issues w/ finding a graceful shutdown command. `shutdown now` wasn't working for some reason - it says it is shutting down but then doesn't? I think pfSense expects the "halt" command from its custom CLI program to be called first. However, the force shutdown didn't seem to be an issue.

**Comment by rylagek** [comment]
Successful generic build in about 9 minutes. I'm not concerned with force shutdown vs using `halt` first. Good work!
